# Generated by Django 4.0.3 on 2022-04-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('company_ticker', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('purchase_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('selling_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('selling_time', models.TimeField()),
                ('profit_loss', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
